// <auto-generated />
namespace Week8Lab.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class postchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postchange));
        
        string IMigrationMetadata.Id
        {
            get { return "201512130747092_post change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
